name: food_deliver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  collection: ^1.19.0
  flutter_credit_card: ^4.0.1
  intl: ^0.20.2
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/images/desserts/
    - lib/images/nonveg/
    - lib/images/seafood/
    - lib/images/snacks/
    - lib/images/veg/
