name: food_deliver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"  # ✅ Latest stable Dart version

dependencies:
  flutter:
    sdk: flutter
  upi_india: ^3.0.1 
  flutter_rating_bar: ^4.0.1 

  # ✅ General Packages
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  collection: ^1.19.0
  flutter_credit_card: ^4.0.1
  intl: ^0.20.2

  # ✅ Firebase Packages (Updated)
  firebase_core: ^2.30.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0  # ✅ Correct latest version

flutter:
  uses-material-design: true

  assets:
    - lib/images/logo.png
    - lib/images/desserts/
    - lib/images/nonveg/
    - lib/images/seafood/
    - lib/images/snacks/
    - lib/images/veg/
